---
# Source: templates/dev.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    softwareId: '2f9b03eeffea3bca5a8854168476632699315708'
    softwareName: 'rbb-web-app'
  name: 'rbb-web-app-service'
  namespace: 'code-playground'
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: 'rbb-web-app'
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    softwareId: '2f9b03eeffea3bca5a8854168476632699315708'
    softwareName: 'rbb-web-app'
  name: 'rbb-web-app'
  namespace: 'code-playground'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'rbb-web-app'
  template:
    metadata:
      labels:
        app: 'rbb-web-app'
        environment: 'dev'
        softwareId: '2f9b03eeffea3bca5a8854168476632699315708'
        softwareName: 'rbb-web-app'
      namespace: 'code-playground'
    spec:
      containers:
      - image: 'containers.cisco.com/rbb/rbb-web-app'
        imagePullPolicy: IfNotPresent
        name: 'rbb-web-app'
        ports:
        - containerPort: 8080
---

